
CREATE TABLE COMPANY
(
  ID      VARCHAR(200) NOT NULL COMMENT 'Unique아이디',
  NAME    VARCHAR(200) NOT NULL COMMENT '이름',
  AGE     INT          NULL     COMMENT '나이',
  ADDRESS VARCHAR(200) NULL     COMMENT '주소',
  SALARY  INT          NOT NULL COMMENT '급여',
  PRIMARY KEY (ID)
) COMMENT '회사 구성원';

CREATE TABLE DEPARTMENT
(
  ID     VARCHAR(200) NOT NULL COMMENT 'Unique 아이디',
  DEPT   VARCHAR(200) NOT NULL COMMENT '부서',
  EMP_ID VARCHAR(200) NOT NULL COMMENT 'Unique아이디',
  PRIMARY KEY (ID)
) COMMENT '공통 부서';

ALTER TABLE DEPARTMENT
  ADD CONSTRAINT FK_COMPANY_TO_DEPARTMENT
    FOREIGN KEY (EMP_ID)
    REFERENCES COMPANY (ID);
